name: Static Code Analysis

on:
    push:
        branches:
            - main

jobs:
    static_code_analysis:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./src/
        strategy:
            matrix:
                python-version: [3.11.2]
        
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
        
            - name: Set up python
              uses: actions/setup-python@v4
              with:
                python-version: ${{ matrix.python-version }}

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install black isort
        
            - name: Format code with black
              run: black .

            - name: Sort imports with isort
              run: isort .

            - name: Commit changes
              run: |
                git config --global user.name "Tomas-Wardoloff"
                git config --global user.email "tomaswardoloff@gmail.com"
                git add .
                git commit -m "Apply code formatting"

            - name: Push changes
              uses: EndBug/add-and-commit@v4
              with:
                branch: format-code
                author_name: ${{ github.actor }}
                author_email: ${{ github.actor }}@users.noreply.github.com
                token: ${{ secrets.GITHUB_TOKEN }}

            - name: Create pull request
              uses: peter-evans/create-pull-request@v3
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
                branch: format-code
                title: "Code Formatting"
                body: "Apply code formatting using black and isort"